/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as AfiliadaIndexRouteImport } from './routes/afiliada.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as PerfilTransacoesRouteImport } from './routes/perfil.transacoes'
import { Route as PerfilFavoritosRouteImport } from './routes/perfil.favoritos'
import { Route as PerfilEnderecosRouteImport } from './routes/perfil.enderecos'
import { Route as PerfilConfiguracoesRouteImport } from './routes/perfil.configuracoes'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AfiliadaLoginRouteImport } from './routes/afiliada.login'
import { Route as AfiliadaCadastroRouteImport } from './routes/afiliada.cadastro'
import { Route as AdminSincronizacaoRouteImport } from './routes/admin.sincronizacao'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminOrganizarRouteImport } from './routes/admin.organizar'
import { Route as AdminNotificacoesRouteImport } from './routes/admin.notificacoes'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGatewayRouteImport } from './routes/admin.gateway'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminChatbotRouteImport } from './routes/admin.chatbot'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBiRouteImport } from './routes/admin.bi'
import { Route as AdminAfiliadasRouteImport } from './routes/admin.afiliadas'
import { Route as CheckoutPixIdRouteImport } from './routes/checkout.pix.$id'
import { Route as ApiLovableBotStatusRouteImport } from './routes/api/lovable-bot/status'
import { Route as ApiLovableBotNotifyRouteImport } from './routes/api/lovable-bot/notify'
import { Route as ApiLovableBotLogoutRouteImport } from './routes/api/lovable-bot/logout'
import { Route as ApiBotStatusRouteImport } from './routes/api/bot/status'
import { Route as ApiBotNotifyRouteImport } from './routes/api/bot/notify'
import { Route as ApiBotLogoutRouteImport } from './routes/api/bot/logout'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadaIndexRoute = AfiliadaIndexRouteImport.update({
  id: '/afiliada/',
  path: '/afiliada/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilTransacoesRoute = PerfilTransacoesRouteImport.update({
  id: '/perfil/transacoes',
  path: '/perfil/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilFavoritosRoute = PerfilFavoritosRouteImport.update({
  id: '/perfil/favoritos',
  path: '/perfil/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilEnderecosRoute = PerfilEnderecosRouteImport.update({
  id: '/perfil/enderecos',
  path: '/perfil/enderecos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilConfiguracoesRoute = PerfilConfiguracoesRouteImport.update({
  id: '/perfil/configuracoes',
  path: '/perfil/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadaLoginRoute = AfiliadaLoginRouteImport.update({
  id: '/afiliada/login',
  path: '/afiliada/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadaCadastroRoute = AfiliadaCadastroRouteImport.update({
  id: '/afiliada/cadastro',
  path: '/afiliada/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSincronizacaoRoute = AdminSincronizacaoRouteImport.update({
  id: '/admin/sincronizacao',
  path: '/admin/sincronizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizarRoute = AdminOrganizarRouteImport.update({
  id: '/admin/organizar',
  path: '/admin/organizar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificacoesRoute = AdminNotificacoesRouteImport.update({
  id: '/admin/notificacoes',
  path: '/admin/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGatewayRoute = AdminGatewayRouteImport.update({
  id: '/admin/gateway',
  path: '/admin/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/admin/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/admin/cupons',
  path: '/admin/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatbotRoute = AdminChatbotRouteImport.update({
  id: '/admin/chatbot',
  path: '/admin/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBiRoute = AdminBiRouteImport.update({
  id: '/admin/bi',
  path: '/admin/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAfiliadasRoute = AdminAfiliadasRouteImport.update({
  id: '/admin/afiliadas',
  path: '/admin/afiliadas',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPixIdRoute = CheckoutPixIdRouteImport.update({
  id: '/pix/$id',
  path: '/pix/$id',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiLovableBotStatusRoute = ApiLovableBotStatusRouteImport.update({
  id: '/api/lovable-bot/status',
  path: '/api/lovable-bot/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLovableBotNotifyRoute = ApiLovableBotNotifyRouteImport.update({
  id: '/api/lovable-bot/notify',
  path: '/api/lovable-bot/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLovableBotLogoutRoute = ApiLovableBotLogoutRouteImport.update({
  id: '/api/lovable-bot/logout',
  path: '/api/lovable-bot/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotStatusRoute = ApiBotStatusRouteImport.update({
  id: '/api/bot/status',
  path: '/api/bot/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotNotifyRoute = ApiBotNotifyRouteImport.update({
  id: '/api/bot/notify',
  path: '/api/bot/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotLogoutRoute = ApiBotLogoutRouteImport.update({
  id: '/api/bot/logout',
  path: '/api/bot/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/pedidos': typeof PedidosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/suporte': typeof SuporteRoute
  '/admin/afiliadas': typeof AdminAfiliadasRoute
  '/admin/bi': typeof AdminBiRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/gateway': typeof AdminGatewayRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/organizar': typeof AdminOrganizarRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/sincronizacao': typeof AdminSincronizacaoRoute
  '/afiliada/cadastro': typeof AfiliadaCadastroRoute
  '/afiliada/login': typeof AfiliadaLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesRoute
  '/perfil/enderecos': typeof PerfilEnderecosRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil/transacoes': typeof PerfilTransacoesRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/afiliada/': typeof AfiliadaIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/api/bot/logout': typeof ApiBotLogoutRoute
  '/api/bot/notify': typeof ApiBotNotifyRoute
  '/api/bot/status': typeof ApiBotStatusRoute
  '/api/lovable-bot/logout': typeof ApiLovableBotLogoutRoute
  '/api/lovable-bot/notify': typeof ApiLovableBotNotifyRoute
  '/api/lovable-bot/status': typeof ApiLovableBotStatusRoute
  '/checkout/pix/$id': typeof CheckoutPixIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/pedidos': typeof PedidosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/suporte': typeof SuporteRoute
  '/admin/afiliadas': typeof AdminAfiliadasRoute
  '/admin/bi': typeof AdminBiRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/gateway': typeof AdminGatewayRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/organizar': typeof AdminOrganizarRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/sincronizacao': typeof AdminSincronizacaoRoute
  '/afiliada/cadastro': typeof AfiliadaCadastroRoute
  '/afiliada/login': typeof AfiliadaLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesRoute
  '/perfil/enderecos': typeof PerfilEnderecosRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil/transacoes': typeof PerfilTransacoesRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin': typeof AdminIndexRoute
  '/afiliada': typeof AfiliadaIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/api/bot/logout': typeof ApiBotLogoutRoute
  '/api/bot/notify': typeof ApiBotNotifyRoute
  '/api/bot/status': typeof ApiBotStatusRoute
  '/api/lovable-bot/logout': typeof ApiLovableBotLogoutRoute
  '/api/lovable-bot/notify': typeof ApiLovableBotNotifyRoute
  '/api/lovable-bot/status': typeof ApiLovableBotStatusRoute
  '/checkout/pix/$id': typeof CheckoutPixIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/pedidos': typeof PedidosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/suporte': typeof SuporteRoute
  '/admin/afiliadas': typeof AdminAfiliadasRoute
  '/admin/bi': typeof AdminBiRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/gateway': typeof AdminGatewayRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/organizar': typeof AdminOrganizarRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/sincronizacao': typeof AdminSincronizacaoRoute
  '/afiliada/cadastro': typeof AfiliadaCadastroRoute
  '/afiliada/login': typeof AfiliadaLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesRoute
  '/perfil/enderecos': typeof PerfilEnderecosRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil/transacoes': typeof PerfilTransacoesRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/afiliada/': typeof AfiliadaIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/api/bot/logout': typeof ApiBotLogoutRoute
  '/api/bot/notify': typeof ApiBotNotifyRoute
  '/api/bot/status': typeof ApiBotStatusRoute
  '/api/lovable-bot/logout': typeof ApiLovableBotLogoutRoute
  '/api/lovable-bot/notify': typeof ApiLovableBotNotifyRoute
  '/api/lovable-bot/status': typeof ApiLovableBotStatusRoute
  '/checkout/pix/$id': typeof CheckoutPixIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apresentacao'
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/categorias'
    | '/checkout'
    | '/esqueci-senha'
    | '/login'
    | '/pedidos'
    | '/redefinir-senha'
    | '/suporte'
    | '/admin/afiliadas'
    | '/admin/bi'
    | '/admin/categorias'
    | '/admin/chatbot'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/gateway'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/notificacoes'
    | '/admin/organizar'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/sincronizacao'
    | '/afiliada/cadastro'
    | '/afiliada/login'
    | '/categoria/$slug'
    | '/pedido/$id'
    | '/perfil/configuracoes'
    | '/perfil/enderecos'
    | '/perfil/favoritos'
    | '/perfil/transacoes'
    | '/produto/$id'
    | '/admin/'
    | '/afiliada/'
    | '/perfil/'
    | '/api/bot/logout'
    | '/api/bot/notify'
    | '/api/bot/status'
    | '/api/lovable-bot/logout'
    | '/api/lovable-bot/notify'
    | '/api/lovable-bot/status'
    | '/checkout/pix/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apresentacao'
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/categorias'
    | '/checkout'
    | '/esqueci-senha'
    | '/login'
    | '/pedidos'
    | '/redefinir-senha'
    | '/suporte'
    | '/admin/afiliadas'
    | '/admin/bi'
    | '/admin/categorias'
    | '/admin/chatbot'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/gateway'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/notificacoes'
    | '/admin/organizar'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/sincronizacao'
    | '/afiliada/cadastro'
    | '/afiliada/login'
    | '/categoria/$slug'
    | '/pedido/$id'
    | '/perfil/configuracoes'
    | '/perfil/enderecos'
    | '/perfil/favoritos'
    | '/perfil/transacoes'
    | '/produto/$id'
    | '/admin'
    | '/afiliada'
    | '/perfil'
    | '/api/bot/logout'
    | '/api/bot/notify'
    | '/api/bot/status'
    | '/api/lovable-bot/logout'
    | '/api/lovable-bot/notify'
    | '/api/lovable-bot/status'
    | '/checkout/pix/$id'
  id:
    | '__root__'
    | '/'
    | '/apresentacao'
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/categorias'
    | '/checkout'
    | '/esqueci-senha'
    | '/login'
    | '/pedidos'
    | '/redefinir-senha'
    | '/suporte'
    | '/admin/afiliadas'
    | '/admin/bi'
    | '/admin/categorias'
    | '/admin/chatbot'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/gateway'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/notificacoes'
    | '/admin/organizar'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/sincronizacao'
    | '/afiliada/cadastro'
    | '/afiliada/login'
    | '/categoria/$slug'
    | '/pedido/$id'
    | '/perfil/configuracoes'
    | '/perfil/enderecos'
    | '/perfil/favoritos'
    | '/perfil/transacoes'
    | '/produto/$id'
    | '/admin/'
    | '/afiliada/'
    | '/perfil/'
    | '/api/bot/logout'
    | '/api/bot/notify'
    | '/api/bot/status'
    | '/api/lovable-bot/logout'
    | '/api/lovable-bot/notify'
    | '/api/lovable-bot/status'
    | '/checkout/pix/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApresentacaoRoute: typeof ApresentacaoRoute
  BuscarRoute: typeof BuscarRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CategoriasRoute: typeof CategoriasRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  PedidosRoute: typeof PedidosRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SuporteRoute: typeof SuporteRoute
  AdminAfiliadasRoute: typeof AdminAfiliadasRoute
  AdminBiRoute: typeof AdminBiRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminChatbotRoute: typeof AdminChatbotRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminGatewayRoute: typeof AdminGatewayRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNotificacoesRoute: typeof AdminNotificacoesRoute
  AdminOrganizarRoute: typeof AdminOrganizarRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminSincronizacaoRoute: typeof AdminSincronizacaoRoute
  AfiliadaCadastroRoute: typeof AfiliadaCadastroRoute
  AfiliadaLoginRoute: typeof AfiliadaLoginRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  PedidoIdRoute: typeof PedidoIdRoute
  PerfilConfiguracoesRoute: typeof PerfilConfiguracoesRoute
  PerfilEnderecosRoute: typeof PerfilEnderecosRoute
  PerfilFavoritosRoute: typeof PerfilFavoritosRoute
  PerfilTransacoesRoute: typeof PerfilTransacoesRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AfiliadaIndexRoute: typeof AfiliadaIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  ApiBotLogoutRoute: typeof ApiBotLogoutRoute
  ApiBotNotifyRoute: typeof ApiBotNotifyRoute
  ApiBotStatusRoute: typeof ApiBotStatusRoute
  ApiLovableBotLogoutRoute: typeof ApiLovableBotLogoutRoute
  ApiLovableBotNotifyRoute: typeof ApiLovableBotNotifyRoute
  ApiLovableBotStatusRoute: typeof ApiLovableBotStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliada/': {
      id: '/afiliada/'
      path: '/afiliada'
      fullPath: '/afiliada/'
      preLoaderRoute: typeof AfiliadaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/transacoes': {
      id: '/perfil/transacoes'
      path: '/perfil/transacoes'
      fullPath: '/perfil/transacoes'
      preLoaderRoute: typeof PerfilTransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/favoritos': {
      id: '/perfil/favoritos'
      path: '/perfil/favoritos'
      fullPath: '/perfil/favoritos'
      preLoaderRoute: typeof PerfilFavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/enderecos': {
      id: '/perfil/enderecos'
      path: '/perfil/enderecos'
      fullPath: '/perfil/enderecos'
      preLoaderRoute: typeof PerfilEnderecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/configuracoes': {
      id: '/perfil/configuracoes'
      path: '/perfil/configuracoes'
      fullPath: '/perfil/configuracoes'
      preLoaderRoute: typeof PerfilConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliada/login': {
      id: '/afiliada/login'
      path: '/afiliada/login'
      fullPath: '/afiliada/login'
      preLoaderRoute: typeof AfiliadaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliada/cadastro': {
      id: '/afiliada/cadastro'
      path: '/afiliada/cadastro'
      fullPath: '/afiliada/cadastro'
      preLoaderRoute: typeof AfiliadaCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sincronizacao': {
      id: '/admin/sincronizacao'
      path: '/admin/sincronizacao'
      fullPath: '/admin/sincronizacao'
      preLoaderRoute: typeof AdminSincronizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizar': {
      id: '/admin/organizar'
      path: '/admin/organizar'
      fullPath: '/admin/organizar'
      preLoaderRoute: typeof AdminOrganizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notificacoes': {
      id: '/admin/notificacoes'
      path: '/admin/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AdminNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gateway': {
      id: '/admin/gateway'
      path: '/admin/gateway'
      fullPath: '/admin/gateway'
      preLoaderRoute: typeof AdminGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/admin/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chatbot': {
      id: '/admin/chatbot'
      path: '/admin/chatbot'
      fullPath: '/admin/chatbot'
      preLoaderRoute: typeof AdminChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bi': {
      id: '/admin/bi'
      path: '/admin/bi'
      fullPath: '/admin/bi'
      preLoaderRoute: typeof AdminBiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/afiliadas': {
      id: '/admin/afiliadas'
      path: '/admin/afiliadas'
      fullPath: '/admin/afiliadas'
      preLoaderRoute: typeof AdminAfiliadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pix/$id': {
      id: '/checkout/pix/$id'
      path: '/pix/$id'
      fullPath: '/checkout/pix/$id'
      preLoaderRoute: typeof CheckoutPixIdRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/lovable-bot/status': {
      id: '/api/lovable-bot/status'
      path: '/api/lovable-bot/status'
      fullPath: '/api/lovable-bot/status'
      preLoaderRoute: typeof ApiLovableBotStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lovable-bot/notify': {
      id: '/api/lovable-bot/notify'
      path: '/api/lovable-bot/notify'
      fullPath: '/api/lovable-bot/notify'
      preLoaderRoute: typeof ApiLovableBotNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lovable-bot/logout': {
      id: '/api/lovable-bot/logout'
      path: '/api/lovable-bot/logout'
      fullPath: '/api/lovable-bot/logout'
      preLoaderRoute: typeof ApiLovableBotLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/status': {
      id: '/api/bot/status'
      path: '/api/bot/status'
      fullPath: '/api/bot/status'
      preLoaderRoute: typeof ApiBotStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/notify': {
      id: '/api/bot/notify'
      path: '/api/bot/notify'
      fullPath: '/api/bot/notify'
      preLoaderRoute: typeof ApiBotNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/logout': {
      id: '/api/bot/logout'
      path: '/api/bot/logout'
      fullPath: '/api/bot/logout'
      preLoaderRoute: typeof ApiBotLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutPixIdRoute: typeof CheckoutPixIdRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutPixIdRoute: CheckoutPixIdRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApresentacaoRoute: ApresentacaoRoute,
  BuscarRoute: BuscarRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CategoriasRoute: CategoriasRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  PedidosRoute: PedidosRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SuporteRoute: SuporteRoute,
  AdminAfiliadasRoute: AdminAfiliadasRoute,
  AdminBiRoute: AdminBiRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminChatbotRoute: AdminChatbotRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminGatewayRoute: AdminGatewayRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNotificacoesRoute: AdminNotificacoesRoute,
  AdminOrganizarRoute: AdminOrganizarRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminSincronizacaoRoute: AdminSincronizacaoRoute,
  AfiliadaCadastroRoute: AfiliadaCadastroRoute,
  AfiliadaLoginRoute: AfiliadaLoginRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  PedidoIdRoute: PedidoIdRoute,
  PerfilConfiguracoesRoute: PerfilConfiguracoesRoute,
  PerfilEnderecosRoute: PerfilEnderecosRoute,
  PerfilFavoritosRoute: PerfilFavoritosRoute,
  PerfilTransacoesRoute: PerfilTransacoesRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AfiliadaIndexRoute: AfiliadaIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  ApiBotLogoutRoute: ApiBotLogoutRoute,
  ApiBotNotifyRoute: ApiBotNotifyRoute,
  ApiBotStatusRoute: ApiBotStatusRoute,
  ApiLovableBotLogoutRoute: ApiLovableBotLogoutRoute,
  ApiLovableBotNotifyRoute: ApiLovableBotNotifyRoute,
  ApiLovableBotStatusRoute: ApiLovableBotStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
