// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glezvjgtzplflzevclor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZXp2amd0enBsZmx6ZXZjbG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwNDYyNjMsImV4cCI6MjA5MzYyMjI2M30._bbOrxbqoZfH9rRyyLDgudUfbCOAWqfZqwTUYWFjzsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});